visions = [
    "Die Flammen tanzen - ein Wandel naht." "Lakota: Pȟéta wakȟáŋ kiŋ iglúwiŋ, owíčakȟe waŋ bluhá.",
    "Ein Schatten folgt dir, doch er ist kein Feind.",
    "Die Ahnen beobachten deinen nächsten Schritt.",
    "Ein neuer Pfad öffnet sich im Morgengrauen.",
    "Der Rauch zieht nach Norden – eine Entscheidung naht.",
    "Ein Schatten folgt deinem Schritt, doch er will lehren.",
    "Die Trommel verstummt, damit du dich selbst hörst.",
    "Ein alter Pfad ruft, auch wenn er überwuchert ist.",
    "Die Flamme flackert – Zweifel und Hoffnung stehen nah beieinander.",
    "Ein Tier kreuzt deinen Weg. Achte auf sein Verhalten.",
    "Der Wind trägt deinen Namen weiter, als du glaubst.",
    "Ein Kreis schließt sich, ein neuer beginnt.",
    "Die Ahnen warten nicht – sie beobachten.",
    "Ein Opfer wird gefordert, doch nicht aus Fleisch.",
    "Die Ahnen treten näher – sie erwarten Demut, keinen Mut.",
    "Dein Geist steht zwischen zwei Welten. Verweile nicht zu lange.",
    "Der Rauch zeigt dir etwas, das andere nicht sehen dürfen.",
    "Ein Zeichen wurde dir gegeben, doch seine Last gehört dir allein.",
    "Die Trommel schlägt außerhalb der Zeit – höre genau hin.",
    "Nicht jeder Geist will verehrt werden.",
    "Ein Fehler aus der Vergangenheit fordert Erinnerung, keine Schuld.",
    "Die Ahnen prüfen nicht deine Stärke, sondern deine Stille.",
    "Was du heute siehst, darf morgen nicht gesprochen werden.",
    "Der Pfad des Heilers ist einsam, aber notwendig."
]
